### ISSUE TITLE
Build User Test Grid

### ISSUE THREAD

**Issue by May-Lee** [tahoe-lafs/community#10]
Notes (turn into steps):
Prefer Nix over Ansible
Need to fix Tahoe instrumentation related to deployment In order to determine if Test Grid working or not 
Also related to Allmydata.com 
Run the latest version of Tahoe
Would like monitoring
Classes of uses:    
we get usage/behavior data                    
other people can use it reliably
Need to determine reasonable amount of time it can be used - one week?
6 - 12
Test grid discussion revisit     
Suggested: make sure there is a roadmap before beginning     

It would be 
1) setting up Tahoe and 2) Server infrastructure ops     

We have the servers (See private Cryptpad infra doc)  We could plan this to take place within the next 1 - 2 months 

Update this:
https://tahoe-lafs.org/trac/tahoe-lafs/wiki/TestGrid

**Comment by meejah** [comment]
>  Need to determine reasonable amount of time it can be used - one week?

What does this mean exactly? Is this like "how often do we wipe data" or ...?

**Comment by sajith** [comment]
If we want to the test grid to test Tahoe-LAFS itself, we should be careful in calling this a _user_ test grid.

**Comment by meejah** [comment]
> If we want to the test grid to test Tahoe-LAFS itself, we should be careful in calling this a user test grid.

Why not both?

I think the main use-case of a test-grid that's accessible to random client machines is:
- someone finds Tahoe-LAFS
- they want to try it out.
- they are excited enough to download the software
- they are *not* excited enough to create their own grid

Since the goal is "try some stuff out" we need to be very explicit that there is *zero* chance your data will be saved. We should probably wipe it on some schedule just so that remains true. Ideally we'd turn on garbage-collection with some very short lease timeouts (e.g. 4 hours?) but IIRC lease-times are hard-coded at 31 days currently.

I think ideally, the grid would be re-created upon every merge to master (so that it is always running the latest). If it's easiest to wipe the grid during re-deployment, cool we should do that.

**Comment by sajith** [comment]
Yes, both.  I meant to say that we should make it very clear that the test grid won't be exclusively for user testing. :-)

I too imagine we might want to automate deployments such that the test grid will be always running the current master branch of Tahoe-LAFS.  Sometimes deployments might wipe user data, or make it inaccessible.  We should make it very clear that such events are expected to happen, and not just periodic house-cleaning.

**Comment by exarkun** [comment]
It sounds like someone might update the NixOS packaging of Tahoe-LAFS for us, including the support in NixOS for configuring Tahoe-LAFS nodes.

If so, that will make deploying Tahoe-LAFS on NixOS extremely easy.

My understanding of the current/old NixOS configuration support for Tahoe-LAFS is that it was fairly rigid.  It supported exactly some set of options.  It would be nice if, when doing any work to update this, some flexibility could be added.  It's nice that NixOS explicitly supports some parts of Tahoe-LAFS configuration because that means it can apply some correctness checking and reject invalid configurations before it even writes a tahoe.cfg (let alone tries to run Tahoe-LAFS).  However, it would be nice to have an escape hatch from this system which allows somewhat arbitrary configuration to be added.  This provides two benefits:

* It allows developers who want to try out new configuration options that they might want to add to Tahoe-LAFS to do so more easily.  Similarly, it allows users who want to take advantage of new options for which the NixOS configuration system has not yet been updated to do so.
* It allows for the configuration of plugins to Tahoe-LAFS which have their own configuration sections.  While all these plugins could have explicit first-class support in NixOS, by their nature as plugins it is less reasonable to expect NixOS to have full coverage here.  At the moment this is not an *entirely* academic point as there is one point of extension in Tahoe-LAFS.  Perhaps in the future Tahoe-LAFS will become even more modular and have more plugin points.

**Comment by exarkun** [comment]
It sounds like someone might update the NixOS packaging of Tahoe-LAFS for us, including the support in NixOS for configuring Tahoe-LAFS nodes.

If so, that will make deploying Tahoe-LAFS on NixOS extremely easy.

My understanding of the current/old NixOS configuration support for Tahoe-LAFS is that it was fairly rigid.  It supported exactly some set of options.  It would be nice if, when doing any work to update this, some flexibility could be added.  It's nice that NixOS explicitly supports some parts of Tahoe-LAFS configuration because that means it can apply some correctness checking and reject invalid configurations before it even writes a tahoe.cfg (let alone tries to run Tahoe-LAFS).  However, it would be nice to have an escape hatch from this system which allows somewhat arbitrary configuration to be added.  This provides two benefits:

* It allows developers who want to try out new configuration options that they might want to add to Tahoe-LAFS to do so more easily.  Similarly, it allows users who want to take advantage of new options for which the NixOS configuration system has not yet been updated to do so.
* It allows for the configuration of plugins to Tahoe-LAFS which have their own configuration sections.  While all these plugins could have explicit first-class support in NixOS, by their nature as plugins it is less reasonable to expect NixOS to have full coverage here.  At the moment this is not an *entirely* academic point as there is one point of extension in Tahoe-LAFS.  Perhaps in the future Tahoe-LAFS will become even more modular and have more plugin points.

**Comment by exarkun** [comment]
It sounds like someone might update the NixOS packaging of Tahoe-LAFS for us, including the support in NixOS for configuring Tahoe-LAFS nodes.

If so, that will make deploying Tahoe-LAFS on NixOS extremely easy.

My understanding of the current/old NixOS configuration support for Tahoe-LAFS is that it was fairly rigid.  It supported exactly some set of options.  It would be nice if, when doing any work to update this, some flexibility could be added.  It's nice that NixOS explicitly supports some parts of Tahoe-LAFS configuration because that means it can apply some correctness checking and reject invalid configurations before it even writes a tahoe.cfg (let alone tries to run Tahoe-LAFS).  However, it would be nice to have an escape hatch from this system which allows somewhat arbitrary configuration to be added.  This provides two benefits:

* It allows developers who want to try out new configuration options that they might want to add to Tahoe-LAFS to do so more easily.  Similarly, it allows users who want to take advantage of new options for which the NixOS configuration system has not yet been updated to do so.
* It allows for the configuration of plugins to Tahoe-LAFS which have their own configuration sections.  While all these plugins could have explicit first-class support in NixOS, by their nature as plugins it is less reasonable to expect NixOS to have full coverage here.  At the moment this is not an *entirely* academic point as there is one point of extension in Tahoe-LAFS.  Perhaps in the future Tahoe-LAFS will become even more modular and have more plugin points.

**Comment by exarkun** [comment]
It sounds like someone might update the NixOS packaging of Tahoe-LAFS for us, including the support in NixOS for configuring Tahoe-LAFS nodes.

If so, that will make deploying Tahoe-LAFS on NixOS extremely easy.

My understanding of the current/old NixOS configuration support for Tahoe-LAFS is that it was fairly rigid.  It supported exactly some set of options.  It would be nice if, when doing any work to update this, some flexibility could be added.  It's nice that NixOS explicitly supports some parts of Tahoe-LAFS configuration because that means it can apply some correctness checking and reject invalid configurations before it even writes a tahoe.cfg (let alone tries to run Tahoe-LAFS).  However, it would be nice to have an escape hatch from this system which allows somewhat arbitrary configuration to be added.  This provides two benefits:

* It allows developers who want to try out new configuration options that they might want to add to Tahoe-LAFS to do so more easily.  Similarly, it allows users who want to take advantage of new options for which the NixOS configuration system has not yet been updated to do so.
* It allows for the configuration of plugins to Tahoe-LAFS which have their own configuration sections.  While all these plugins could have explicit first-class support in NixOS, by their nature as plugins it is less reasonable to expect NixOS to have full coverage here.  At the moment this is not an *entirely* academic point as there is one point of extension in Tahoe-LAFS.  Perhaps in the future Tahoe-LAFS will become even more modular and have more plugin points.

**Comment by aaronjanse** [comment]
I've pushed a package for Python 3 Tahoe-LAFS to my fork of Nixpkgs:

https://github.com/aaronjanse/nixpkgs/tree/aj2021jul-tahoe

Next steps for me are:
1. Update the NixOS module to accept arbitrary settings. This is straightforward
2. Submit a PR to Nixpkgs

**Comment by May-Lee** [comment]
@aaronjanse I opened a ticket to capture which tests are failing in the Nix build environment. 

https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3752#ticket

**Comment by aaronjanse** [comment]
Thank you!

**Comment by Mic92** [comment]
New version is now part of nixpkgs-unstable.

**Comment by aaronjanse** [comment]
Update: I hope to get a PR submitted tomorrow for the NixOS module

**Comment by ghost** [comment]
hey, hello. 

this issue refers to monitoring, and  I used to play (and still do) with icinga2/icingaweb2.  If that's the kind of monitoring the ticket is refering to, and if you're looking for someone to help set it up, i'd glad to do so

also, FWIW, i'm running a public introducer and 2 "share" nodes.. in case it might help revive the testgrid ? ... :>

kr,

**Comment by meejah** [comment]
Welcome, @complotist 

That certainly sounds related! It would of course be great to have some sort of monitoring of the test-grid so that the operators can know when there is a problem.

**Comment by exarkun** [comment]
@May-Lee when you have a chance could you add my SSH public key to the root user on the test grid Hetzner host?  You can find my key at https://github.com/exarkun.keys

Then I can do the following:

* cross-grade the host to NixOS
* deploy the test grid configuration from https://github.com/tahoe-lafs/infrastructure onto it

And then I guess we will have a test grid.

**Comment by exarkun** [comment]
@meejah Can you point testgrid.tahoe-lafs.org at 157.90.125.177 and 2a01:4f8:1c0c:61a3::1?  (Or if you have an idea for a better name then feel free to use that and let me know)

**Comment by exarkun** [comment]
> @meejah Can you point testgrid.tahoe-lafs.org at 157.90.125.177 and 2a01:4f8:1c0c:61a3::1? (Or if you have an idea for a better name then feel free to use that and let me know)

@meejah :ping_pong:

**Comment by meejah** [comment]
Sorry, just saw this -- added those A and AAAA records.

**Comment by exarkun** [comment]
An initial deployment configuration is defined by https://github.com/tahoe-lafs/infrastructure/pull/1

Reviews are welcome.  I'll merge next Monday if no reviews are forthcoming.

**Comment by May-Lee** [comment]
would be great if @aaronjanse would be up for doing a review

**Comment by aaronjanse** [comment]
Ooh I'd love to! I'll take a look tomorrow, since it's late here :-)

**Comment by exarkun** [comment]
> An initial deployment configuration is defined by [tahoe-lafs/infrastructure#1](https://github.com/tahoe-lafs/infrastructure/pull/1)
> 
> Reviews are welcome. I'll merge next Monday if no reviews are forthcoming.

Just a friendly (and final) reminder that I plan to merge today but I'd love a review first (@meejah @sajith @aaronjanse @Mic92 @complotist).

**Comment by meejah** [comment]
reviewed, sort of (but if anyone w/ more Nix knowledge is motivated, they should also review :)

**Comment by sajith** [comment]
Nix is unfamiliar territory to me too, but we can't let that be an obstacle, can we? I too have left some comments. :-)

Sorry about not meeting the deadline yesterday. Was busy banging my head against the desk about other unrelated... stuff.
